# action.yml
name: 'Get Next Tag'
description: 'Calculate the next tag'
inputs:
  release-type: # id of input 1
    description: 'The release type: Major, Minor, or HotFix'
    required: true
    default: 'Minor'
  current-tag: # id of input 2
    description: 'The current last tag'
    required: true
    default: ''
outputs:
  next-tag: # id of output
    description: 'The next (incremented) tag'
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.release-type }}
    - ${{ inputs.current-tag }}
